{
 "title": "3.1. LB Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "subscription",
    "label": "subscription",
    "query": {}
   },
   {
    "name": "resourceGroup_LB",
    "label": "resourceGroup_LB",
    "query": {}
   },
   {
    "name": "loadBalancer",
    "label": "LB",
    "query": {}
   },
   {
    "name": "resourceGroup_AGW",
    "label": "resourceGroup_AGW",
    "query": {}
   },
   {
    "name": "agw",
    "label": "AGW",
    "query": {}
   },
   {
    "name": "resourceGroup_VPN",
    "label": "resourceGroup_VPN",
    "query": {}
   },
   {
    "name": "VPN",
    "label": "VPN",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "LB Probe ($loadBalancer)",
   "type": "stat",
   "description": "LB Probe 전체 합산",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "loadBalancer",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "$loadBalancer",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "region": "",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Metrics : $loadBalancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "loadBalancer" },
  {
   "title": "LB Backend List",
   "type": "table",
   "description": "백엔드를 내부 IP로 구성한 경우 IP만,\n\n백엔드를 NIC로 구성한 경우 NIC명 + IP로 출력",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{resourcename}} ({{FrontendIPAddress}})",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [
       {
        "dimension": "FrontendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "region": "",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where type contains \"Microsoft.Network/loadBalancers\" and name =~ $loadBalancer\r\n| mv-expand  bepools = properties.backendAddressPools\r\n| project benic1 = bepools.properties.loadBalancerBackendAddresses\r\n| mv-expand  benic2 = benic1\r\n| project bepoolList = benic2.properties.ipAddress\r\n| where isnotnull(bepoolList)\r\n| project tostring(bepoolList)"
     },
     "subscription": "$subscription",
     "subscriptions": [ "$subscription" ]
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{resourcename}} ({{FrontendIPAddress}})",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [
       {
        "dimension": "FrontendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "region": "",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "azureResourceGraph": {
      "query": "// NIC\r\nresources\r\n| where type contains \"Microsoft.Network/loadBalancers\" and name =~ $loadBalancer\r\n| mv-expand  bepools = properties.backendAddressPools\r\n| project benic1 = bepools.properties.loadBalancerBackendAddresses\r\n| mv-expand  benic2 = benic1\r\n| project ipconfId = tostring(benic2.properties.networkInterfaceIPConfiguration.id)\r\n| join kind=leftouter hint.strategy=shuffle(\r\n  resources\r\n  | where type =~ \"Microsoft.Network/networkInterfaces\"\r\n  | mv-expand ipconf = properties.ipConfigurations\r\n  | project privateIp = ipconf.properties.privateIPAddress, ipconfId = tostring(ipconf.id)) on ipconfId \r\n| parse ipconfId with * \"/networkInterfaces/\" nicName \"/\" *\r\n| where isnotempty(nicName)\r\n| project bepoolList = strcat(nicName, \" (\", privateIp, \")\")"
     },
     "subscription": "$subscription",
     "subscriptions": [ "$subscription" ]
    }
   ]
  },
  {
   "title": "LB Frontend Probe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{resourcename}} ({{FrontendIPAddress}})",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [
       {
        "dimension": "FrontendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "region": "",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "LB Backend Probe ($loadBalancer)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{BackendIPAddress}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [
       {
        "dimension": "BackendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "region": "",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "LB Bytes ($loadBalancer)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{FrontendIPAddress}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "FrontendIPAddress",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ByteCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resources": [
       {
        "metricNamespace": "microsoft.network/loadbalancers",
        "resourceGroup": "$resourceGroup_LB",
        "resourceName": "$loadBalancer",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  }
 ]
}